<a href="https://colab.research.google.com/github/tokaho/ESTR3108-Sepsis-diagnosis-from-pairwise-single-cell-RNA/blob/master/COlab%20test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

mount google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv(r'/content/drive/My Drive/estr3108 project/labely.csv.gz',compression ="gzip")
label1 = df.to_numpy()
print('len of label1',len(label1))
print(label1)

label2 = genfromtxt('/content/drive/My Drive/estr3108 project/labely.csv.gz', delimiter=',', dtype=None, encoding=None,skip_header=0)          
print('\n','len of label2',len(label2))
print(label2)

len of label1 122556
[['Leuk-UTI']
 ['Control']
 ['Control']
 ...
 ['Bac-SEP']
 ['Bac-SEP']
 ['Bac-SEP']]

 len of label2 122557
['Control' 'Leuk-UTI' 'Control' ... 'Bac-SEP' 'Bac-SEP' 'Bac-SEP']


In [ ]:
i

18

prepare data

In [ ]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

In [ ]:
float_samples=samples[1:].astype('float64')

array([], dtype=int64)

In [ ]:
meta_data = genfromtxt('/content/drive/My Drive/estr3108 project/scp_meta.txt', names=True, dtype=None, encoding="utf8")
print(meta_data[meta_data['NAME']=='AAACCTGAGACGCTTT-1']['Cohort'])
meta_data


['Control']


array([('TYPE', 'group', 'group', 'group', 'group', 'group'),
       ('AAACCTGAGACGCTTT-1', 'T', 'TS2', 'Control', 'CD45', 'P18F'),
       ('AAACCTGAGCAATCTC-1', 'B', 'BS1', 'Leuk-UTI', 'CD45', 'P20'), ...,
       ('TTTGTCAAGTGTTTGC-35', 'Mono', 'MS2', 'Bac-SEP', 'CD45', 'E16'),
       ('TTTGTCACAGCTTAAC-35', 'Mono', 'MS1', 'Bac-SEP', 'CD45', 'E16'),
       ('TTTGTCAGTTATGCGT-35', 'Mono', 'MS1', 'Bac-SEP', 'CD45', 'E16')],
      dtype=[('NAME', '<U19'), ('Cell_Type', '<U13'), ('Cell_State', '<U5'), ('Cohort', '<U9'), ('Sort', '<U5'), ('Patient', '<U6')])

In [ ]:
#import pandas as pd
#matrix_data =pd.read_csv('/content/drive/My Drive/estr3108 project/scp_gex_matrix.csv.gz', compression='gzip',error_bad_lines=False, nrows=10)
matrix_Data = genfromtxt('scp_gex_matrix.csv.gz', delimiter=',', names=True, dtype=None, encoding=None,skip_header=0)


In [ ]:
#import pandas as pd
#matrix_data =pd.read_csv('/content/drive/My Drive/estr3108 project/out.csv.gz', compression='gzip',error_bad_lines=False, nrows=10,skiprows=0)
matrix_Data = genfromtxt('/content/drive/My Drive/estr3108 project/out_tr.csv.gz',max_rows=10, names=True,delimiter=',', dtype=float, encoding=None,skip_header=0)#total 122558 rows
label = genfromtxt('/content/drive/My Drive/estr3108 project/labely.csv.gz', delimiter=',', dtype=None, encoding=None,skip_header=0)                  #total 122557 labels


In [ ]:
#print(matrix_Data)
rna=np.delete(matrix_data.columns,0)
label = np.array([])
for each in rna:
  label = np.append(label,meta_data[meta_data['NAME']==each]['Cohort'][0])
label

array(['Control', 'Leuk-UTI', 'Control', ..., 'Bac-SEP', 'Bac-SEP',
       'Bac-SEP'], dtype='<U32')

In [ ]:
np.savetxt("/content/drive/My Drive/estr3108 project/labely.csv.gz", label, fmt='%s')


In [ ]:
matrix_Data

TAKE transpose of csv

In [ ]:
import pandas as pd
N = 22858 
batch_size = 50

from_file = '/content/drive/My Drive/estr3108 project/scp_gex_matrix.csv.gz'
to_file = 'my_large_file_transposed2.csv'
for batch in range(N//batch_size + bool(N%batch_size)):
    lcol = batch * batch_size
    rcol = min(N, lcol+batch_size)
    data = pd.read_csv(from_file, usecols=range(lcol, rcol))
    with open(to_file, 'a') as _f:
        data.T.to_csv(_f, header=False)

read csv file and remove empty row

In [ ]:

count=0
done=0
batch=1
head = True


for df in pd.read_csv("/content/drive/My Drive/estr3108 project/scp_gex_matrix.csv.gz",compression ="gzip", chunksize=batch,index_col=False):

    df = df[(df.loc[:, df.columns != "GENE"].T != 0).any()] # remove all zero rows
    df.to_csv('out.csv.gz', index=False,compression="gzip",mode="a",header= head)  
    head=False
    count=count+batch
    done=done+len(df)
    print("finished ",count," record, added",done," record")
    




#continue processing on z

testing 

In [ ]:
data = {'GENE':  ["ABC", "DEF" ,"aa"],
        'rna': [0., 1.,2.],
        'dna': [0., 1.,3.],
        }

df = pd.DataFrame (data)
print(df)
print(df.T.dtypes)
df = df[(df.loc[:, df.columns != "GENE"].T != 0).any()]
print(len(df))

  GENE  rna  dna
0  ABC  0.0  0.0
1  DEF  1.0  1.0
2   aa  2.0  3.0
0    object
1    object
2    object
dtype: object
2


In [ ]:


a=np.array([['GENE','AAACCTGAGACGCTTT-1','TTTGTCAAGTGTTTGC-35','TTTGTCAGTTATGCGT-35'],['test1',1,0,99],['test2',2,1.1,99]])

a=np.transpose(a)

a=np.delete(a,0,axis=0)

b = [meta_data[meta_data['NAME']==row[0]]['Cohort'][0] for row in a ] 
a=np.delete(a,0,axis=1)

# split a dataset into train and test sets
print(a,b)
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(a, b, test_size=0.33, random_state=1)
print(X_train, X_test, y_train, y_test)




print(X_train, X_test, y_train, y_test)

[['1' '2']
 ['0' '1.1']
 ['99' '99']] ['Control', 'Bac-SEP', 'Bac-SEP']
[['99' '99']
 ['0' '1.1']] [['1' '2']] ['Bac-SEP', 'Bac-SEP'] ['Control']
[['99' '99']
 ['0' '1.1']] [['1' '2']] ['Bac-SEP', 'Bac-SEP'] ['Control']


In [ ]:
print("start")
X = np.empty((0,122558)) # Will have memory error soon
for df in pd.read_csv(r"/content/drive/My Drive/estr3108 project/scp_gex_matrix.csv.gz",compression ="gzip", chunksize=10):
    df = df[(df.loc[:, df.columns != "GENE"].T != 0).any()] # remove all zero rows
    print(df)
    arr = df.to_numpy()
    X = np.vstack([X,arr]) # error after 450 rows 
    print(X)
    break


idx = np.argwhere(np.all(X[..., :] ==0,axis = 0)) #find index of zero columns
X=np.vstack([df.columns.to_numpy(),X])
X = np.delete(X,idx,axis = 1) #remove all zero columns

#continue processing on X

start
            GENE  AAACCTGAGACGCTTT-1  ...  TTTGTCACAGCTTAAC-35  TTTGTCAGTTATGCGT-35
0   RP11-34P13.7                 0.0  ...                  0.0                  0.0
1   RP11-34P13.8                 0.0  ...                  0.0                  0.0
2   RP11-34P13.9                 0.0  ...                  0.0                  0.0
3     FO538757.3                 0.0  ...                  0.0                  0.0
4     FO538757.2                 0.0  ...                  0.0                  2.0
5     AP006222.2                 0.0  ...                  0.0                  0.0
6  RP4-669L17.10                 0.0  ...                  0.0                  0.0
7   RP5-857K21.4                 0.0  ...                  0.0                  0.0
8  RP11-206L10.9                 0.0  ...                  0.0                  0.0
9         FAM87B                 0.0  ...                  0.0                  0.0

[10 rows x 122558 columns]
[['RP11-34P13.7' 0.0 0.0 ... 0.0 0.0 0.0]


Multi class classification (single label)

In [ ]:

from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC 
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style


In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

#get first 999 samples
X=matrix_Data[1:1000]
y=label[:999]

#change label to sequences of number
encoder = MultiLabelBinarizer()
transfomed_label = encoder.fit_transform(y)
print(transfomed_label)
y=transfomed_label

[[0 1 0 ... 1 1 0]
 [1 0 1 ... 0 0 1]
 [0 1 0 ... 1 1 0]
 ...
 [0 1 0 ... 1 1 0]
 [0 1 0 ... 1 1 0]
 [1 0 1 ... 0 0 1]]


In [ ]:
X=X.tolist()

In [ ]:
#separate test and train cases
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)
#print(X_train, X_test, y_train, y_test)

In [ ]:
#start training
clf = OneVsRestClassifier(SVC()).fit(X_train, y_train)
print('done')

done


In [ ]:
#score
#print("Training:"+str(clf.score(X_train,y_train)))
print("Test:"+str(clf.score(X_test,y_test)))

Test:0.88


In [ ]:
#check if whether all ans are the same :(((())))
ans=clf.predict(X_test)
#temp= [0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0]
#ans=ans[(ans!=temp).any()]
print(ans[:10])

[[1 0 1 1 1 1 1 1 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 1 0 0 0 0 0 0 1 1 1 1 1 0]]


In [ ]:
#save model
from joblib import dump
dump(clf, '/content/drive/My Drive/estr3108 project/model/20201003_1000samples.joblib',compress=True) 

['/content/drive/My Drive/estr3108 project/model/20201003_1000samples.joblib']

In [ ]:
#load model
from joblib import load
clf=load( '/content/drive/My Drive/estr3108 project/model/20201003_1000sample.joblib') 

get P value

In [ ]:
t_stat,pvalue = stats.ttest_ind(con_sample, case_sample, axis = 0, equal_var=True, nan_policy='raise')
rejected, P_fdr = sm.fdrcorrection(pvalue, alpha=0.05, method='indep', is_sorted=False)
